package org.julienjnnqin.luxmateapp.data.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import org.julienjnnqin.luxmateapp.domain.entity.Message
import org.julienjnnqin.luxmateapp.domain.entity.StructuredResponse

@Serializable
data class ChatMessage(
    val id: String,
    val role: String,  // "user" or "assistant"
    val content: String,
    @SerialName("structured_response")
    val structuredResponse: LLMResponse? = null,
    @SerialName("created_at")
    val createdAt: String
)

@Serializable
data class SendMessageRequest(
    val content: String
)

@Serializable
data class SendMessageResponse(
    val message: String? = null,
    @SerialName("structured_response")
    val structuredResponse: LLMResponse? = null,
    val role: String = "assistant"
) {
    fun toDomain(): Message {
        return Message(
            id = "", // ID will be generated by the backend
            content = this.message ?: "",
            timestamp = "", // Timestamp will be set by the backend
            isFromUser = role == "user",
            structuredData = structuredResponse?.let {
                StructuredResponse(
                    greeting = it.greeting,
                    mainPoint = it.mainPoint,
                    details = it.details,
                    analogy = it.analogy,
                    nextStep = it.nextStep
                )
            }
        )
    }
}

